"""
backend/descriptors/pipeline/xtb_cosmo/xtb_runner.py

XTB計算を実行するラッパークラス
"""
import os
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Optional, Tuple, List, Dict
import logging

from .config import XTBConfig

logger = logging.getLogger(__name__)

# Windows での xtb クラッシュ時ポップアップ（アプリケーションエラー）を抑制する
if os.name == 'nt':
    try:
        import ctypes
        SEM_FAILCRITICALERRORS = 0x0001
        SEM_NOGPFAULTERRORBOX = 0x0002
        SEM_NOOPENFILEERRORBOX = 0x8000
        ctypes.windll.kernel32.SetErrorMode(
            SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX
        )
    except Exception:
        pass

# クラッシュ検出時に2回目以降の実行をスキップするためのフラグ
_XTB_RUNNER_BROKEN = False

class XTBRunner:
    def __init__(self, config: XTBConfig):
        self.config = config
        self._xtb_path = self._find_xtb_binary()
        
    def _find_xtb_binary(self) -> str:
        if path := os.getenv("XTB_PATH"):
            if shutil.which(path):
                return path
        if path := shutil.which("xtb"):
            return path
        common_paths = [
            "/usr/local/bin/xtb",
            "/opt/xtb/bin/xtb",
            str(Path.home() / ".local/bin/xtb"),
        ]
        for p in common_paths:
            if Path(p).exists():
                return p
        # For testing or gracefully failing, we might not want to throw an exception directly 
        # but let the pipeline handle it. For now, we raise a RuntimeError as per original design.
        raise RuntimeError("xtb binary not found.")
        
    def run_single(self, smiles: str, work_dir: Optional[Path] = None, molecule_id: Optional[str] = None) -> Tuple[bool, dict, List[str]]:
        global _XTB_RUNNER_BROKEN
        warnings_list = []
        result: Dict = {}
        
        if _XTB_RUNNER_BROKEN:
            warnings_list.append("XTBが以前にクラッシュしたため、この分子の計算をスキップしました（システム環境/DLLエラーなど）")
            return False, {}, warnings_list
            
        try:
            if work_dir is None:
                work_dir = Path(tempfile.mkdtemp(prefix="chemai_xtb_"))
                cleanup = True
            else:
                work_dir.mkdir(parents=True, exist_ok=True)
                cleanup = False
                
            mol_id = molecule_id or f"mol_{hash(smiles) & 0xFFFF:04X}"
            
            # 3D structure generation
            try:
                # We need to ensure we can load RDKit
                from rdkit import Chem
                from rdkit.Chem import AllChem
                
                mol = Chem.MolFromSmiles(smiles)
                if mol is None:
                    return False, {}, [f"Invalid SMILES: {smiles}"]
                mol = Chem.AddHs(mol)
                res = AllChem.EmbedMolecule(mol, randomSeed=42)
                if res != 0:
                    return False, {}, [f"3D embedding failed for: {smiles}"]
                if self.config.optimization:
                    AllChem.MMFFOptimizeMolecule(mol)
            except Exception as e:
                return False, {}, [f"3D structure generation error: {e}"]
                
            xyz_path = work_dir / f"{mol_id}.xyz"
            with open(xyz_path, 'w') as f:
                f.write(f"{mol.GetNumAtoms()}\n")
                f.write(f"Generated by chemai2: {smiles}\n")
                conf = mol.GetConformer()
                for atom in mol.GetAtoms():
                    pos = conf.GetAtomPosition(atom.GetIdx())
                    f.write(f"{atom.GetSymbol():2s} {pos.x:10.5f} {pos.y:10.5f} {pos.z:10.5f}\n")
                    
            cmd = [self._xtb_path, str(xyz_path)]
            cmd.extend(["--method", self.config.method.value])
            if self.config.charge != 0:
                cmd.extend(["--charge", str(self.config.charge)])
            if self.config.multiplicity != 1:
                cmd.extend(["--uhf", str(self.config.multiplicity - 1)])
            if self.config.solvation_model:
                cmd.extend(["--alpb", self.config.solvation_model])
            if self.config.optimization:
                cmd.extend(["--opt", "--maxiter", str(self.config.max_iterations), "--tolerance", str(self.config.convergence_tolerance)])
            if self.config.frequency:
                cmd.append("--hess")
            if self.config.output_cosmo:
                cmd.append("--cosmo")
            cmd.extend(["--parallel", str(self.config.n_threads)])
            # --memory can occasionally cause issues with some xtb versions, skipping for now unless strictly needed
            
            # We mock the safe_subprocess_run using subprocess directly for the real implementation
            # if safe_subprocess_run from utils is not fully defined
            try:
                kwargs_sub = {}
                if os.name == "nt":
                    kwargs_sub["creationflags"] = getattr(subprocess, "CREATE_NO_WINDOW", 0x08000000)

                proc_result = subprocess.run(
                    cmd, cwd=work_dir, timeout=self.config.timeout_seconds,
                    capture_output=True, text=True, check=False,
                    **kwargs_sub
                )
                
                if proc_result.returncode in (3221225794, -1073741502, 3221225749, -1073741515, 3221225477, -1073741819):
                    _XTB_RUNNER_BROKEN = True
                    warnings_list.append(f"XTBがシステムエラーでクラッシュしました。(returncode: {proc_result.returncode}) 以降の分子はスキップします。")
                    return False, {}, warnings_list
                
                if proc_result.returncode != 0:
                    warnings_list.append(f"XTB execution failed with return code {proc_result.returncode}: {proc_result.stderr}")
                    if self.config.retry_on_failure and self.config.fallback_method:
                        return self._run_with_fallback(smiles, work_dir, mol_id, warnings_list)
                    return False, {}, warnings_list

                output_text = proc_result.stdout
            except subprocess.TimeoutExpired:
                warnings_list.append("XTB execution timeout")
                return False, {}, warnings_list
                
            result = self._parse_xtb_output(work_dir, mol_id, output_text)
            
            if not result.get("optimization_converged", True):
                warnings_list.append("幾何最適化が収束しませんでした")
                if self.config.retry_on_failure:
                    return self._run_with_relaxed_params(smiles, work_dir, mol_id, warnings_list)
                    
            result["success"] = True
            result["molecule_id"] = mol_id
            result["smiles"] = smiles
            
            if self.config.output_cosmo:
                # The generated cosmo file is often named xtb.cosmo
                cosmo_path = work_dir / f"{mol_id}.cosmo"
                work_dir / f"{xyz_path.name}.cosmo" # or xtb.cosmo depending on version
                
                # Try finding it
                found_cosmo = None
                for cfile in work_dir.glob("*.cosmo"):
                    found_cosmo = cfile
                    break
                    
                if found_cosmo:
                    found_cosmo.rename(cosmo_path)
                    result["cosmo_file"] = str(cosmo_path)
                else:
                    warnings_list.append(".cosmoファイルが出力されませんでした")
                    
            return True, result, warnings_list
            
        except Exception as e:
            logger.exception(f"XTB calculation error: {e}")
            return False, {}, [str(e)]
        finally:
            if cleanup and work_dir.exists():
                shutil.rmtree(work_dir, ignore_errors=True)

    def _parse_xtb_output(self, work_dir: Path, mol_id: str, content: str) -> dict:
        result = {}
        import re
        energy_match = re.search(r'FINAL ENERGY:\s+([-\d.]+)\s+Eh', content)
        if energy_match:
            result["energy_eh"] = float(energy_match.group(1))
            result["energy_kcal_mol"] = float(energy_match.group(1)) * 627.509
        result["optimization_converged"] = "GEOMETRY OPTIMIZATION CONVERGED" in content
        warning_lines = [line.strip() for line in content.split('\n') if 'WARNING' in line.upper()]
        result["xtb_warnings"] = warning_lines[:10]
        return result
        
    def _run_with_fallback(self, smiles: str, work_dir: Path, mol_id: str, warnings: List[str]) -> Tuple[bool, dict, List[str]]:
        original = self.config.method
        self.config.method = self.config.fallback_method
        try:
            return self.run_single(smiles, work_dir, mol_id)
        finally:
            self.config.method = original
            
    def _run_with_relaxed_params(self, smiles: str, work_dir: Path, mol_id: str, warnings: List[str]) -> Tuple[bool, dict, List[str]]:
        orig_tol = self.config.convergence_tolerance
        orig_iter = self.config.max_iterations
        self.config.convergence_tolerance *= 10
        self.config.max_iterations *= 2
        try:
            return self.run_single(smiles, work_dir, mol_id)
        finally:
            self.config.convergence_tolerance = orig_tol
            self.config.max_iterations = orig_iter
