# Generated by Django 6.0 on 2026-03-18 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='新しい解析', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('n_rows', models.IntegerField(default=0)),
                ('n_cols', models.IntegerField(default=0)),
                ('target_col', models.CharField(blank=True, default='', max_length=200)),
                ('smiles_col', models.CharField(blank=True, default='', max_length=200)),
                ('task_type', models.CharField(choices=[('regression', '回帰'), ('classification', '分類')], default='regression', max_length=20)),
                ('selected_descriptors', models.JSONField(blank=True, default=list)),
                ('precalc_data_path', models.CharField(blank=True, default='', max_length=500)),
                ('analysis_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('created', '作成済'), ('data_loaded', 'データ読込済'), ('descriptors_calculated', '記述子計算済'), ('running', '解析実行中'), ('completed', '完了'), ('error', 'エラー')], default='created', max_length=30)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
